### ISSUE TITLE
Python Avro libraries updates for ES 11.0.1 onwards

### ISSUE THREAD

**Issue by jesusmah** [ibm-cloud-architecture/refarch-eda-tools#15]
I got this working against Apicurio registry in ES 11.0.1 with the following tweaks:

- I updated the registry endpoint to use the confluent compatible APIs only, (as there are some clashes between the ES APIs and the confluent APIs) by adding /api/ccompat to the end of the schema registry URL, e.g.

   ```
   export SCHEMA_REGISTRY_URL=https://<scram-username>:<scram-pw>@development-ibm-es-ac-reg-external-es.<server>/api/ccompat
   ```
- I flattened the schema before I pre-registered it, by removing the newline chars and any extra whitespace. E.g. the original file contained:
  ```
  {
      "namespace": "ibm.eda.default",
      "doc": "Default Message's value Avro data schema",
      "type":"record",
      "name":"defaultValue",
      "fields":[
              {
                  "name": "message",
                  "type":"string",
                  "doc": "Any string"
              }
       ]
  }
  ```
  But I created a new file as a single line like this:
  ```
  {"type": "record", "name": "defaultValue", "namespace": "ibm.eda.default", "fields": [{"type": "string", "name": "message", "doc": "Any string"}], "doc": "Default Message's value Avro data schema"}
  ```
  This is will allow the confluent client lookup method to find the schema, as it flattens the content before submitting to Apicurio, and I believe Apicurio just does a direct comparison.

- I changed line 34 of the KcAvroProducer.py class to match the arguments required by the latest version of the confluent_kafka library that I downloaded (which was version 1.9.0), which has the SchemaRegistryClient object first and the contents of the schema file second, e.g:
  ```
  self.value_serializer = AvroSerializer(self.schema_registry_client, value_schema, None, {'auto.register.schemas': False})
  ```

With these changes I was able to run the client happily.

I also tried with auto-registering the schema (changing the line above to `AvroSerializer(self.schema_registry_client, value_schema, None, None)`) which also worked correctly when using the above changes.

Hope this helps.

**Comment by jbcodeforce** [comment]
Thank you Jesus,
Please commit your changes.
